packages:
  github.com/a-novel/service-json-keys/v3/internal/core:
    config:
      all: true
      pkgname: coremocks
      dir: internal/core/mocks
      filename: mocks.go
  github.com/a-novel/service-json-keys/v3/internal/handlers:
    config:
      all: true
      pkgname: handlersmocks
      dir: internal/handlers/mocks
      filename: mocks.go
  github.com/a-novel/service-json-keys/v3/pkg/go:
    config:
      all: true
      pkgname: pkgmocks
      dir: pkg/go/mocks
      filename: mocks.go
