packages:
  github.com/a-novel/service-json-keys/v2/internal/services:
    config:
      all: true
      pkgname: servicesmocks
      dir: internal/services/mocks
      filename: mocks.go
  github.com/a-novel/service-json-keys/v2/internal/handlers:
    config:
      all: true
      pkgname: handlersmocks
      dir: internal/handlers/mocks
      filename: mocks.go
  github.com/a-novel/service-json-keys/v2/pkg:
    config:
      all: true
      pkgname: pkgmocks
      dir: internal/pkg/mocks
      filename: mocks.go
