// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel-kit/jwt/v2/jwa"
	"github.com/a-novel/service-json-keys/v2/internal/core"
	"github.com/a-novel/service-json-keys/v2/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJwkExportLocalSource creates a new instance of MockJwkExportLocalSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkExportLocalSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkExportLocalSource {
	mock := &MockJwkExportLocalSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkExportLocalSource is an autogenerated mock type for the JwkExportLocalSource type
type MockJwkExportLocalSource struct {
	mock.Mock
}

type MockJwkExportLocalSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkExportLocalSource) EXPECT() *MockJwkExportLocalSource_Expecter {
	return &MockJwkExportLocalSource_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkExportLocalSource
func (_mock *MockJwkExportLocalSource) Exec(ctx context.Context, request *core.JwkSearchRequest) ([]*core.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkSearchRequest) ([]*core.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkSearchRequest) []*core.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkExportLocalSource_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkExportLocalSource_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JwkSearchRequest
func (_e *MockJwkExportLocalSource_Expecter) Exec(ctx any, request any) *MockJwkExportLocalSource_Exec_Call {
	return &MockJwkExportLocalSource_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkExportLocalSource_Exec_Call) Run(run func(ctx context.Context, request *core.JwkSearchRequest)) *MockJwkExportLocalSource_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkExportLocalSource_Exec_Call) Return(vs []*core.Jwk, err error) *MockJwkExportLocalSource_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockJwkExportLocalSource_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JwkSearchRequest) ([]*core.Jwk, error)) *MockJwkExportLocalSource_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGenDaoSearch creates a new instance of MockJwkGenDaoSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenDaoSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenDaoSearch {
	mock := &MockJwkGenDaoSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenDaoSearch is an autogenerated mock type for the JwkGenDaoSearch type
type MockJwkGenDaoSearch struct {
	mock.Mock
}

type MockJwkGenDaoSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenDaoSearch) EXPECT() *MockJwkGenDaoSearch_Expecter {
	return &MockJwkGenDaoSearch_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenDaoSearch
func (_mock *MockJwkGenDaoSearch) Exec(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) ([]*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) []*dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenDaoSearch_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenDaoSearch_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSearchRequest
func (_e *MockJwkGenDaoSearch_Expecter) Exec(ctx any, request any) *MockJwkGenDaoSearch_Exec_Call {
	return &MockJwkGenDaoSearch_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenDaoSearch_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSearchRequest)) *MockJwkGenDaoSearch_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenDaoSearch_Exec_Call) Return(jwks []*dao.Jwk, err error) *MockJwkGenDaoSearch_Exec_Call {
	_c.Call.Return(jwks, err)
	return _c
}

func (_c *MockJwkGenDaoSearch_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error)) *MockJwkGenDaoSearch_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGenDaoInsert creates a new instance of MockJwkGenDaoInsert. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenDaoInsert(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenDaoInsert {
	mock := &MockJwkGenDaoInsert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenDaoInsert is an autogenerated mock type for the JwkGenDaoInsert type
type MockJwkGenDaoInsert struct {
	mock.Mock
}

type MockJwkGenDaoInsert_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenDaoInsert) EXPECT() *MockJwkGenDaoInsert_Expecter {
	return &MockJwkGenDaoInsert_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenDaoInsert
func (_mock *MockJwkGenDaoInsert) Exec(ctx context.Context, request *dao.JwkInsertRequest) (*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkInsertRequest) (*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkInsertRequest) *dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenDaoInsert_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenDaoInsert_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkInsertRequest
func (_e *MockJwkGenDaoInsert_Expecter) Exec(ctx any, request any) *MockJwkGenDaoInsert_Exec_Call {
	return &MockJwkGenDaoInsert_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenDaoInsert_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkInsertRequest)) *MockJwkGenDaoInsert_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenDaoInsert_Exec_Call) Return(jwk *dao.Jwk, err error) *MockJwkGenDaoInsert_Exec_Call {
	_c.Call.Return(jwk, err)
	return _c
}

func (_c *MockJwkGenDaoInsert_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkInsertRequest) (*dao.Jwk, error)) *MockJwkGenDaoInsert_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGenServiceExtract creates a new instance of MockJwkGenServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenServiceExtract {
	mock := &MockJwkGenServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenServiceExtract is an autogenerated mock type for the JwkGenServiceExtract type
type MockJwkGenServiceExtract struct {
	mock.Mock
}

type MockJwkGenServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenServiceExtract) EXPECT() *MockJwkGenServiceExtract_Expecter {
	return &MockJwkGenServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenServiceExtract
func (_mock *MockJwkGenServiceExtract) Exec(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) (*core.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) *core.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JwkExtractRequest
func (_e *MockJwkGenServiceExtract_Expecter) Exec(ctx any, request any) *MockJwkGenServiceExtract_Exec_Call {
	return &MockJwkGenServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *core.JwkExtractRequest)) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenServiceExtract_Exec_Call) Return(v *core.Jwk, err error) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkGenServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error)) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkPrivateSource creates a new instance of MockJwkPrivateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkPrivateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkPrivateSource {
	mock := &MockJwkPrivateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkPrivateSource is an autogenerated mock type for the JwkPrivateSource type
type MockJwkPrivateSource struct {
	mock.Mock
}

type MockJwkPrivateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkPrivateSource) EXPECT() *MockJwkPrivateSource_Expecter {
	return &MockJwkPrivateSource_Expecter{mock: &_m.Mock}
}

// SearchKeys provides a mock function for the type MockJwkPrivateSource
func (_mock *MockJwkPrivateSource) SearchKeys(ctx context.Context, usage string) ([]*jwa.JWK, error) {
	ret := _mock.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for SearchKeys")
	}

	var r0 []*jwa.JWK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*jwa.JWK, error)); ok {
		return returnFunc(ctx, usage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*jwa.JWK); ok {
		r0 = returnFunc(ctx, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jwa.JWK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, usage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkPrivateSource_SearchKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKeys'
type MockJwkPrivateSource_SearchKeys_Call struct {
	*mock.Call
}

// SearchKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - usage string
func (_e *MockJwkPrivateSource_Expecter) SearchKeys(ctx any, usage any) *MockJwkPrivateSource_SearchKeys_Call {
	return &MockJwkPrivateSource_SearchKeys_Call{Call: _e.mock.On("SearchKeys", ctx, usage)}
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) Run(run func(ctx context.Context, usage string)) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) Return(jWKs []*jwa.JWK, err error) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Return(jWKs, err)
	return _c
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) RunAndReturn(run func(ctx context.Context, usage string) ([]*jwa.JWK, error)) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkPublicSource creates a new instance of MockJwkPublicSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkPublicSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkPublicSource {
	mock := &MockJwkPublicSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkPublicSource is an autogenerated mock type for the JwkPublicSource type
type MockJwkPublicSource struct {
	mock.Mock
}

type MockJwkPublicSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkPublicSource) EXPECT() *MockJwkPublicSource_Expecter {
	return &MockJwkPublicSource_Expecter{mock: &_m.Mock}
}

// SearchKeys provides a mock function for the type MockJwkPublicSource
func (_mock *MockJwkPublicSource) SearchKeys(ctx context.Context, usage string) ([]*jwa.JWK, error) {
	ret := _mock.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for SearchKeys")
	}

	var r0 []*jwa.JWK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*jwa.JWK, error)); ok {
		return returnFunc(ctx, usage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*jwa.JWK); ok {
		r0 = returnFunc(ctx, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jwa.JWK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, usage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkPublicSource_SearchKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKeys'
type MockJwkPublicSource_SearchKeys_Call struct {
	*mock.Call
}

// SearchKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - usage string
func (_e *MockJwkPublicSource_Expecter) SearchKeys(ctx any, usage any) *MockJwkPublicSource_SearchKeys_Call {
	return &MockJwkPublicSource_SearchKeys_Call{Call: _e.mock.On("SearchKeys", ctx, usage)}
}

func (_c *MockJwkPublicSource_SearchKeys_Call) Run(run func(ctx context.Context, usage string)) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkPublicSource_SearchKeys_Call) Return(jWKs []*jwa.JWK, err error) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Return(jWKs, err)
	return _c
}

func (_c *MockJwkPublicSource_SearchKeys_Call) RunAndReturn(run func(ctx context.Context, usage string) ([]*jwa.JWK, error)) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSearchDao creates a new instance of MockJwkSearchDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSearchDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSearchDao {
	mock := &MockJwkSearchDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSearchDao is an autogenerated mock type for the JwkSearchDao type
type MockJwkSearchDao struct {
	mock.Mock
}

type MockJwkSearchDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSearchDao) EXPECT() *MockJwkSearchDao_Expecter {
	return &MockJwkSearchDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSearchDao
func (_mock *MockJwkSearchDao) Exec(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) ([]*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) []*dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSearchDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSearchDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSearchRequest
func (_e *MockJwkSearchDao_Expecter) Exec(ctx any, request any) *MockJwkSearchDao_Exec_Call {
	return &MockJwkSearchDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSearchDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSearchRequest)) *MockJwkSearchDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSearchDao_Exec_Call) Return(jwks []*dao.Jwk, err error) *MockJwkSearchDao_Exec_Call {
	_c.Call.Return(jwks, err)
	return _c
}

func (_c *MockJwkSearchDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error)) *MockJwkSearchDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSearchServiceExtract creates a new instance of MockJwkSearchServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSearchServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSearchServiceExtract {
	mock := &MockJwkSearchServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSearchServiceExtract is an autogenerated mock type for the JwkSearchServiceExtract type
type MockJwkSearchServiceExtract struct {
	mock.Mock
}

type MockJwkSearchServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSearchServiceExtract) EXPECT() *MockJwkSearchServiceExtract_Expecter {
	return &MockJwkSearchServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSearchServiceExtract
func (_mock *MockJwkSearchServiceExtract) Exec(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) (*core.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) *core.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSearchServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSearchServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JwkExtractRequest
func (_e *MockJwkSearchServiceExtract_Expecter) Exec(ctx any, request any) *MockJwkSearchServiceExtract_Exec_Call {
	return &MockJwkSearchServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *core.JwkExtractRequest)) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) Return(v *core.Jwk, err error) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error)) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSelectDao creates a new instance of MockJwkSelectDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSelectDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSelectDao {
	mock := &MockJwkSelectDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSelectDao is an autogenerated mock type for the JwkSelectDao type
type MockJwkSelectDao struct {
	mock.Mock
}

type MockJwkSelectDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSelectDao) EXPECT() *MockJwkSelectDao_Expecter {
	return &MockJwkSelectDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSelectDao
func (_mock *MockJwkSelectDao) Exec(ctx context.Context, request *dao.JwkSelectRequest) (*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSelectRequest) (*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSelectRequest) *dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSelectDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSelectDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSelectRequest
func (_e *MockJwkSelectDao_Expecter) Exec(ctx any, request any) *MockJwkSelectDao_Exec_Call {
	return &MockJwkSelectDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSelectDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSelectRequest)) *MockJwkSelectDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSelectDao_Exec_Call) Return(jwk *dao.Jwk, err error) *MockJwkSelectDao_Exec_Call {
	_c.Call.Return(jwk, err)
	return _c
}

func (_c *MockJwkSelectDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSelectRequest) (*dao.Jwk, error)) *MockJwkSelectDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSelectServiceExtract creates a new instance of MockJwkSelectServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSelectServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSelectServiceExtract {
	mock := &MockJwkSelectServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSelectServiceExtract is an autogenerated mock type for the JwkSelectServiceExtract type
type MockJwkSelectServiceExtract struct {
	mock.Mock
}

type MockJwkSelectServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSelectServiceExtract) EXPECT() *MockJwkSelectServiceExtract_Expecter {
	return &MockJwkSelectServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSelectServiceExtract
func (_mock *MockJwkSelectServiceExtract) Exec(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) (*core.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JwkExtractRequest) *core.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSelectServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSelectServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JwkExtractRequest
func (_e *MockJwkSelectServiceExtract_Expecter) Exec(ctx any, request any) *MockJwkSelectServiceExtract_Exec_Call {
	return &MockJwkSelectServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *core.JwkExtractRequest)) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) Return(v *core.Jwk, err error) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JwkExtractRequest) (*core.Jwk, error)) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}
