// Code generated by ogen, DO NOT EDIT.
package apimodels

type GetPublicKeyRes interface {
	getPublicKeyRes()
}

type HealthcheckRes interface {
	healthcheckRes()
}

type ListPublicKeysRes interface {
	listPublicKeysRes()
}

type PingRes interface {
	pingRes()
}

type SignClaimsRes interface {
	signClaimsRes()
}
