// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: claims_sign.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClaimsSignService_ClaimsSign_FullMethodName = "/ClaimsSignService/ClaimsSign"
)

// ClaimsSignServiceClient is the client API for ClaimsSignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClaimsSignService remotely generates a signed token from claims. The parameters used to
// sign a token depend on the intended usage.
type ClaimsSignServiceClient interface {
	ClaimsSign(ctx context.Context, in *ClaimsSignRequest, opts ...grpc.CallOption) (*ClaimsSignResponse, error)
}

type claimsSignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClaimsSignServiceClient(cc grpc.ClientConnInterface) ClaimsSignServiceClient {
	return &claimsSignServiceClient{cc}
}

func (c *claimsSignServiceClient) ClaimsSign(ctx context.Context, in *ClaimsSignRequest, opts ...grpc.CallOption) (*ClaimsSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimsSignResponse)
	err := c.cc.Invoke(ctx, ClaimsSignService_ClaimsSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClaimsSignServiceServer is the server API for ClaimsSignService service.
// All implementations must embed UnimplementedClaimsSignServiceServer
// for forward compatibility.
//
// ClaimsSignService remotely generates a signed token from claims. The parameters used to
// sign a token depend on the intended usage.
type ClaimsSignServiceServer interface {
	ClaimsSign(context.Context, *ClaimsSignRequest) (*ClaimsSignResponse, error)
	mustEmbedUnimplementedClaimsSignServiceServer()
}

// UnimplementedClaimsSignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClaimsSignServiceServer struct{}

func (UnimplementedClaimsSignServiceServer) ClaimsSign(context.Context, *ClaimsSignRequest) (*ClaimsSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimsSign not implemented")
}
func (UnimplementedClaimsSignServiceServer) mustEmbedUnimplementedClaimsSignServiceServer() {}
func (UnimplementedClaimsSignServiceServer) testEmbeddedByValue()                           {}

// UnsafeClaimsSignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClaimsSignServiceServer will
// result in compilation errors.
type UnsafeClaimsSignServiceServer interface {
	mustEmbedUnimplementedClaimsSignServiceServer()
}

func RegisterClaimsSignServiceServer(s grpc.ServiceRegistrar, srv ClaimsSignServiceServer) {
	// If the following call panics, it indicates UnimplementedClaimsSignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClaimsSignService_ServiceDesc, srv)
}

func _ClaimsSignService_ClaimsSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimsSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClaimsSignServiceServer).ClaimsSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClaimsSignService_ClaimsSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClaimsSignServiceServer).ClaimsSign(ctx, req.(*ClaimsSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClaimsSignService_ServiceDesc is the grpc.ServiceDesc for ClaimsSignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClaimsSignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClaimsSignService",
	HandlerType: (*ClaimsSignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimsSign",
			Handler:    _ClaimsSignService_ClaimsSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "claims_sign.proto",
}
