// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: claims_sign.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimsSignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Intended usage of the token. This determines the parameters and private key used to
	// generate (and later validate) the token.
	Usage string `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	// The payload to sign with the token. Its inner type should remain consistent for a given
	// usage.
	Payload       *anypb.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimsSignRequest) Reset() {
	*x = ClaimsSignRequest{}
	mi := &file_claims_sign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimsSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimsSignRequest) ProtoMessage() {}

func (x *ClaimsSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_claims_sign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimsSignRequest.ProtoReflect.Descriptor instead.
func (*ClaimsSignRequest) Descriptor() ([]byte, []int) {
	return file_claims_sign_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimsSignRequest) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *ClaimsSignRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ClaimsSignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed token, in JWT format, containing the payload.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimsSignResponse) Reset() {
	*x = ClaimsSignResponse{}
	mi := &file_claims_sign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimsSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimsSignResponse) ProtoMessage() {}

func (x *ClaimsSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_claims_sign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimsSignResponse.ProtoReflect.Descriptor instead.
func (*ClaimsSignResponse) Descriptor() ([]byte, []int) {
	return file_claims_sign_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimsSignResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_claims_sign_proto protoreflect.FileDescriptor

const file_claims_sign_proto_rawDesc = "" +
	"\n" +
	"\x11claims_sign.proto\x1a\x19google/protobuf/any.proto\"Y\n" +
	"\x11ClaimsSignRequest\x12\x14\n" +
	"\x05usage\x18\x01 \x01(\tR\x05usage\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"*\n" +
	"\x12ClaimsSignResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2J\n" +
	"\x11ClaimsSignService\x125\n" +
	"\n" +
	"ClaimsSign\x12\x12.ClaimsSignRequest\x1a\x13.ClaimsSignResponseB`B\x0fClaimsSignProtoP\x01ZKgithub.com/a-novel/service-json-keys/v2/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_claims_sign_proto_rawDescOnce sync.Once
	file_claims_sign_proto_rawDescData []byte
)

func file_claims_sign_proto_rawDescGZIP() []byte {
	file_claims_sign_proto_rawDescOnce.Do(func() {
		file_claims_sign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_claims_sign_proto_rawDesc), len(file_claims_sign_proto_rawDesc)))
	})
	return file_claims_sign_proto_rawDescData
}

var file_claims_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_claims_sign_proto_goTypes = []any{
	(*ClaimsSignRequest)(nil),  // 0: ClaimsSignRequest
	(*ClaimsSignResponse)(nil), // 1: ClaimsSignResponse
	(*anypb.Any)(nil),          // 2: google.protobuf.Any
}
var file_claims_sign_proto_depIdxs = []int32{
	2, // 0: ClaimsSignRequest.payload:type_name -> google.protobuf.Any
	0, // 1: ClaimsSignService.ClaimsSign:input_type -> ClaimsSignRequest
	1, // 2: ClaimsSignService.ClaimsSign:output_type -> ClaimsSignResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_claims_sign_proto_init() }
func file_claims_sign_proto_init() {
	if File_claims_sign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_claims_sign_proto_rawDesc), len(file_claims_sign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_claims_sign_proto_goTypes,
		DependencyIndexes: file_claims_sign_proto_depIdxs,
		MessageInfos:      file_claims_sign_proto_msgTypes,
	}.Build()
	File_claims_sign_proto = out.File
	file_claims_sign_proto_goTypes = nil
	file_claims_sign_proto_depIdxs = nil
}
