// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jwk.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Jwk represents a public JSON Web Key. Private key material is never included.
type Jwk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key type identifier. Corresponds to the "kty" JWK parameter (RFC 7517 §4.1).
	// Names the cryptographic algorithm family (e.g., "OKP" for an EdDSA key).
	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	// Intended public key use. Corresponds to the "use" JWK parameter (RFC 7517 §4.2).
	// Typically "sig" for signing keys used to produce or verify JWTs.
	Use string `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	// Permitted key operations. Corresponds to the "key_ops" JWK parameter (RFC 7517 §4.3).
	// A public verification key carries "verify".
	KeyOps []string `protobuf:"bytes,3,rep,name=key_ops,json=keyOps,proto3" json:"key_ops,omitempty"`
	// Algorithm. Corresponds to the "alg" JWK parameter (RFC 7517 §4.4).
	// Identifies the specific signing algorithm (e.g., "EdDSA").
	Alg string `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`
	// Key ID. Corresponds to the "kid" JWK parameter (RFC 7517 §4.5).
	// Carried in the JWT header to identify which key was used to sign the token.
	Kid string `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`
	// Algorithm-specific key parameters (e.g., x and crv for EdDSA keys), encoded as JSON bytes.
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_jwk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_jwk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *Jwk) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *Jwk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Jwk) GetKeyOps() []string {
	if x != nil {
		return x.KeyOps
	}
	return nil
}

func (x *Jwk) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Jwk) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Jwk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_jwk_proto protoreflect.FileDescriptor

const file_jwk_proto_rawDesc = "" +
	"\n" +
	"\tjwk.proto\"\x80\x01\n" +
	"\x03Jwk\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x17\n" +
	"\akey_ops\x18\x03 \x03(\tR\x06keyOps\x12\x10\n" +
	"\x03alg\x18\x04 \x01(\tR\x03alg\x12\x10\n" +
	"\x03kid\x18\x05 \x01(\tR\x03kid\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayloadBYB\bJwkProtoP\x01ZKgithub.com/a-novel/service-json-keys/v2/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_jwk_proto_rawDescOnce sync.Once
	file_jwk_proto_rawDescData []byte
)

func file_jwk_proto_rawDescGZIP() []byte {
	file_jwk_proto_rawDescOnce.Do(func() {
		file_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwk_proto_rawDesc), len(file_jwk_proto_rawDesc)))
	})
	return file_jwk_proto_rawDescData
}

var file_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jwk_proto_goTypes = []any{
	(*Jwk)(nil), // 0: Jwk
}
var file_jwk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwk_proto_init() }
func file_jwk_proto_init() {
	if File_jwk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwk_proto_rawDesc), len(file_jwk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jwk_proto_goTypes,
		DependencyIndexes: file_jwk_proto_depIdxs,
		MessageInfos:      file_jwk_proto_msgTypes,
	}.Build()
	File_jwk_proto = out.File
	file_jwk_proto_goTypes = nil
	file_jwk_proto_depIdxs = nil
}
