// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: jwk_list.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JwkListService_JwkList_FullMethodName = "/JwkListService/JwkList"
)

// JwkListServiceClient is the client API for JwkListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JwkListService lists the active keys for a given usage. The keys are returned in
// creation order (first key in the array is the main key, the rest are legacy).
type JwkListServiceClient interface {
	JwkList(ctx context.Context, in *JwkListRequest, opts ...grpc.CallOption) (*JwkListResponse, error)
}

type jwkListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJwkListServiceClient(cc grpc.ClientConnInterface) JwkListServiceClient {
	return &jwkListServiceClient{cc}
}

func (c *jwkListServiceClient) JwkList(ctx context.Context, in *JwkListRequest, opts ...grpc.CallOption) (*JwkListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JwkListResponse)
	err := c.cc.Invoke(ctx, JwkListService_JwkList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwkListServiceServer is the server API for JwkListService service.
// All implementations must embed UnimplementedJwkListServiceServer
// for forward compatibility.
//
// JwkListService lists the active keys for a given usage. The keys are returned in
// creation order (first key in the array is the main key, the rest are legacy).
type JwkListServiceServer interface {
	JwkList(context.Context, *JwkListRequest) (*JwkListResponse, error)
	mustEmbedUnimplementedJwkListServiceServer()
}

// UnimplementedJwkListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJwkListServiceServer struct{}

func (UnimplementedJwkListServiceServer) JwkList(context.Context, *JwkListRequest) (*JwkListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JwkList not implemented")
}
func (UnimplementedJwkListServiceServer) mustEmbedUnimplementedJwkListServiceServer() {}
func (UnimplementedJwkListServiceServer) testEmbeddedByValue()                        {}

// UnsafeJwkListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwkListServiceServer will
// result in compilation errors.
type UnsafeJwkListServiceServer interface {
	mustEmbedUnimplementedJwkListServiceServer()
}

func RegisterJwkListServiceServer(s grpc.ServiceRegistrar, srv JwkListServiceServer) {
	// If the following call panics, it indicates UnimplementedJwkListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JwkListService_ServiceDesc, srv)
}

func _JwkListService_JwkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwkListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwkListServiceServer).JwkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JwkListService_JwkList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwkListServiceServer).JwkList(ctx, req.(*JwkListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JwkListService_ServiceDesc is the grpc.ServiceDesc for JwkListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JwkListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JwkListService",
	HandlerType: (*JwkListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JwkList",
			Handler:    _JwkListService_JwkList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwk_list.proto",
}
