// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: jwk_get.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwkGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the key to retrieve. This parameter is usually available under the "kid" field
	// of a JSON web token claims / headers.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkGetRequest) Reset() {
	*x = JwkGetRequest{}
	mi := &file_jwk_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkGetRequest) ProtoMessage() {}

func (x *JwkGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwk_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkGetRequest.ProtoReflect.Descriptor instead.
func (*JwkGetRequest) Descriptor() ([]byte, []int) {
	return file_jwk_get_proto_rawDescGZIP(), []int{0}
}

func (x *JwkGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JwkGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key in JSON Web Key (JWK) format.
	Jwk           *Jwk `protobuf:"bytes,1,opt,name=jwk,proto3" json:"jwk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkGetResponse) Reset() {
	*x = JwkGetResponse{}
	mi := &file_jwk_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkGetResponse) ProtoMessage() {}

func (x *JwkGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwk_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkGetResponse.ProtoReflect.Descriptor instead.
func (*JwkGetResponse) Descriptor() ([]byte, []int) {
	return file_jwk_get_proto_rawDescGZIP(), []int{1}
}

func (x *JwkGetResponse) GetJwk() *Jwk {
	if x != nil {
		return x.Jwk
	}
	return nil
}

var File_jwk_get_proto protoreflect.FileDescriptor

const file_jwk_get_proto_rawDesc = "" +
	"\n" +
	"\rjwk_get.proto\x1a\tjwk.proto\"\x1f\n" +
	"\rJwkGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x0eJwkGetResponse\x12\x16\n" +
	"\x03jwk\x18\x01 \x01(\v2\x04.JwkR\x03jwk2:\n" +
	"\rJwkGetService\x12)\n" +
	"\x06JwkGet\x12\x0e.JwkGetRequest\x1a\x0f.JwkGetResponseB\\B\vJwkGetProtoP\x01ZKgithub.com/a-novel/service-json-keys/v2/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_jwk_get_proto_rawDescOnce sync.Once
	file_jwk_get_proto_rawDescData []byte
)

func file_jwk_get_proto_rawDescGZIP() []byte {
	file_jwk_get_proto_rawDescOnce.Do(func() {
		file_jwk_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwk_get_proto_rawDesc), len(file_jwk_get_proto_rawDesc)))
	})
	return file_jwk_get_proto_rawDescData
}

var file_jwk_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jwk_get_proto_goTypes = []any{
	(*JwkGetRequest)(nil),  // 0: JwkGetRequest
	(*JwkGetResponse)(nil), // 1: JwkGetResponse
	(*Jwk)(nil),            // 2: Jwk
}
var file_jwk_get_proto_depIdxs = []int32{
	2, // 0: JwkGetResponse.jwk:type_name -> Jwk
	0, // 1: JwkGetService.JwkGet:input_type -> JwkGetRequest
	1, // 2: JwkGetService.JwkGet:output_type -> JwkGetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jwk_get_proto_init() }
func file_jwk_get_proto_init() {
	if File_jwk_get_proto != nil {
		return
	}
	file_jwk_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwk_get_proto_rawDesc), len(file_jwk_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwk_get_proto_goTypes,
		DependencyIndexes: file_jwk_get_proto_depIdxs,
		MessageInfos:      file_jwk_get_proto_msgTypes,
	}.Build()
	File_jwk_get_proto = out.File
	file_jwk_get_proto_goTypes = nil
	file_jwk_get_proto_depIdxs = nil
}
