// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anovel/jsonkeys/v2/jwk_get.proto

package jsonkeysv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JwkGetRequest identifies the key to retrieve by its key ID.
type JwkGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the key to retrieve. Corresponds to the "kid" field in the JWT header.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkGetRequest) Reset() {
	*x = JwkGetRequest{}
	mi := &file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkGetRequest) ProtoMessage() {}

func (x *JwkGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkGetRequest.ProtoReflect.Descriptor instead.
func (*JwkGetRequest) Descriptor() ([]byte, []int) {
	return file_anovel_jsonkeys_v2_jwk_get_proto_rawDescGZIP(), []int{0}
}

func (x *JwkGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// JwkGetResponse contains the public key matching the requested ID.
type JwkGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested public key.
	Jwk           *Jwk `protobuf:"bytes,1,opt,name=jwk,proto3" json:"jwk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkGetResponse) Reset() {
	*x = JwkGetResponse{}
	mi := &file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkGetResponse) ProtoMessage() {}

func (x *JwkGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkGetResponse.ProtoReflect.Descriptor instead.
func (*JwkGetResponse) Descriptor() ([]byte, []int) {
	return file_anovel_jsonkeys_v2_jwk_get_proto_rawDescGZIP(), []int{1}
}

func (x *JwkGetResponse) GetJwk() *Jwk {
	if x != nil {
		return x.Jwk
	}
	return nil
}

var File_anovel_jsonkeys_v2_jwk_get_proto protoreflect.FileDescriptor

const file_anovel_jsonkeys_v2_jwk_get_proto_rawDesc = "" +
	"\n" +
	" anovel/jsonkeys/v2/jwk_get.proto\x12\x12anovel.jsonkeys.v2\x1a\x1canovel/jsonkeys/v2/jwk.proto\"\x1f\n" +
	"\rJwkGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x0eJwkGetResponse\x12)\n" +
	"\x03jwk\x18\x01 \x01(\v2\x17.anovel.jsonkeys.v2.JwkR\x03jwk2`\n" +
	"\rJwkGetService\x12O\n" +
	"\x06JwkGet\x12!.anovel.jsonkeys.v2.JwkGetRequest\x1a\".anovel.jsonkeys.v2.JwkGetResponseB\xf1\x01\n" +
	"\x16com.anovel.jsonkeys.v2B\vJwkGetProtoP\x01Z`github.com/a-novel/service-json-keys/v2/internal/handlers/protogen/anovel/jsonkeys/v2;jsonkeysv2\xa2\x02\x03AJX\xaa\x02\x12Anovel.Jsonkeys.V2\xca\x02\x12Anovel\\Jsonkeys\\V2\xe2\x02\x1eAnovel\\Jsonkeys\\V2\\GPBMetadata\xea\x02\x14Anovel::Jsonkeys::V2b\x06proto3"

var (
	file_anovel_jsonkeys_v2_jwk_get_proto_rawDescOnce sync.Once
	file_anovel_jsonkeys_v2_jwk_get_proto_rawDescData []byte
)

func file_anovel_jsonkeys_v2_jwk_get_proto_rawDescGZIP() []byte {
	file_anovel_jsonkeys_v2_jwk_get_proto_rawDescOnce.Do(func() {
		file_anovel_jsonkeys_v2_jwk_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_jsonkeys_v2_jwk_get_proto_rawDesc), len(file_anovel_jsonkeys_v2_jwk_get_proto_rawDesc)))
	})
	return file_anovel_jsonkeys_v2_jwk_get_proto_rawDescData
}

var file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_jsonkeys_v2_jwk_get_proto_goTypes = []any{
	(*JwkGetRequest)(nil),  // 0: anovel.jsonkeys.v2.JwkGetRequest
	(*JwkGetResponse)(nil), // 1: anovel.jsonkeys.v2.JwkGetResponse
	(*Jwk)(nil),            // 2: anovel.jsonkeys.v2.Jwk
}
var file_anovel_jsonkeys_v2_jwk_get_proto_depIdxs = []int32{
	2, // 0: anovel.jsonkeys.v2.JwkGetResponse.jwk:type_name -> anovel.jsonkeys.v2.Jwk
	0, // 1: anovel.jsonkeys.v2.JwkGetService.JwkGet:input_type -> anovel.jsonkeys.v2.JwkGetRequest
	1, // 2: anovel.jsonkeys.v2.JwkGetService.JwkGet:output_type -> anovel.jsonkeys.v2.JwkGetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anovel_jsonkeys_v2_jwk_get_proto_init() }
func file_anovel_jsonkeys_v2_jwk_get_proto_init() {
	if File_anovel_jsonkeys_v2_jwk_get_proto != nil {
		return
	}
	file_anovel_jsonkeys_v2_jwk_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_jsonkeys_v2_jwk_get_proto_rawDesc), len(file_anovel_jsonkeys_v2_jwk_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_jsonkeys_v2_jwk_get_proto_goTypes,
		DependencyIndexes: file_anovel_jsonkeys_v2_jwk_get_proto_depIdxs,
		MessageInfos:      file_anovel_jsonkeys_v2_jwk_get_proto_msgTypes,
	}.Build()
	File_anovel_jsonkeys_v2_jwk_get_proto = out.File
	file_anovel_jsonkeys_v2_jwk_get_proto_goTypes = nil
	file_anovel_jsonkeys_v2_jwk_get_proto_depIdxs = nil
}
