services:
  postgres-json-keys:
    build:
      context: ..
      dockerfile: ./builds/database.Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - api
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    volumes:
      - json-keys-postgres-data:/var/lib/postgresql/

  # The Master Key is a secure, 32-bit random secret used to encrypt private JSON keys
  # in the database.
  # This value is a dummy key used for tests. Use your own random key in production.
  service-json-keys:
    build:
      context: ..
      dockerfile: ./builds/standalone.Dockerfile
    ports:
      - "${GRPC_PORT}:8080"
    depends_on:
      - postgres-json-keys
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres-json-keys:5432/json-keys?sslmode=disable
      APP_MASTER_KEY: "${APP_MASTER_KEY}"
    networks:
      - api

networks:
  api:

volumes:
  json-keys-postgres-data:
