// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkgmocks

import (
	"context"

	"github.com/a-novel-kit/golib/grpcf/proto/gen"
	"github.com/a-novel/service-json-keys/v2/pkg"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockClaimsVerifier creates a new instance of MockClaimsVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsVerifier[C any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsVerifier[C] {
	mock := &MockClaimsVerifier[C]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaimsVerifier is an autogenerated mock type for the ClaimsVerifier type
type MockClaimsVerifier[C any] struct {
	mock.Mock
}

type MockClaimsVerifier_Expecter[C any] struct {
	mock *mock.Mock
}

func (_m *MockClaimsVerifier[C]) EXPECT() *MockClaimsVerifier_Expecter[C] {
	return &MockClaimsVerifier_Expecter[C]{mock: &_m.Mock}
}

// VerifyClaims provides a mock function for the type MockClaimsVerifier
func (_mock *MockClaimsVerifier[C]) VerifyClaims(ctx context.Context, req *pkg.VerifyClaimsRequest) (*C, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyClaims")
	}

	var r0 *C
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.VerifyClaimsRequest) (*C, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.VerifyClaimsRequest) *C); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*C)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.VerifyClaimsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaimsVerifier_VerifyClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyClaims'
type MockClaimsVerifier_VerifyClaims_Call[C any] struct {
	*mock.Call
}

// VerifyClaims is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.VerifyClaimsRequest
func (_e *MockClaimsVerifier_Expecter[C]) VerifyClaims(ctx interface{}, req interface{}) *MockClaimsVerifier_VerifyClaims_Call[C] {
	return &MockClaimsVerifier_VerifyClaims_Call[C]{Call: _e.mock.On("VerifyClaims", ctx, req)}
}

func (_c *MockClaimsVerifier_VerifyClaims_Call[C]) Run(run func(ctx context.Context, req *pkg.VerifyClaimsRequest)) *MockClaimsVerifier_VerifyClaims_Call[C] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.VerifyClaimsRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.VerifyClaimsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClaimsVerifier_VerifyClaims_Call[C]) Return(v *C, err error) *MockClaimsVerifier_VerifyClaims_Call[C] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClaimsVerifier_VerifyClaims_Call[C]) RunAndReturn(run func(ctx context.Context, req *pkg.VerifyClaimsRequest) (*C, error)) *MockClaimsVerifier_VerifyClaims_Call[C] {
	_c.Call.Return(run)
	return _c
}

// NewMockBaseClient creates a new instance of MockBaseClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseClient {
	mock := &MockBaseClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseClient is an autogenerated mock type for the BaseClient type
type MockBaseClient struct {
	mock.Mock
}

type MockBaseClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBaseClient) EXPECT() *MockBaseClient_Expecter {
	return &MockBaseClient_Expecter{mock: &_m.Mock}
}

// ClaimsSign provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) ClaimsSign(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption) (*pkg.ClaimsSignResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ClaimsSign")
	}

	var r0 *pkg.ClaimsSignResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) (*pkg.ClaimsSignResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) *pkg.ClaimsSignResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.ClaimsSignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseClient_ClaimsSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimsSign'
type MockBaseClient_ClaimsSign_Call struct {
	*mock.Call
}

// ClaimsSign is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.ClaimsSignRequest
//   - opts ...grpc.CallOption
func (_e *MockBaseClient_Expecter) ClaimsSign(ctx interface{}, req interface{}, opts ...interface{}) *MockBaseClient_ClaimsSign_Call {
	return &MockBaseClient_ClaimsSign_Call{Call: _e.mock.On("ClaimsSign",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockBaseClient_ClaimsSign_Call) Run(run func(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption)) *MockBaseClient_ClaimsSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.ClaimsSignRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.ClaimsSignRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBaseClient_ClaimsSign_Call) Return(v *pkg.ClaimsSignResponse, err error) *MockBaseClient_ClaimsSign_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseClient_ClaimsSign_Call) RunAndReturn(run func(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption) (*pkg.ClaimsSignResponse, error)) *MockBaseClient_ClaimsSign_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) Close() {
	_mock.Called()
	return
}

// MockBaseClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBaseClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBaseClient_Expecter) Close() *MockBaseClient_Close_Call {
	return &MockBaseClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBaseClient_Close_Call) Run(run func()) *MockBaseClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBaseClient_Close_Call) Return() *MockBaseClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBaseClient_Close_Call) RunAndReturn(run func()) *MockBaseClient_Close_Call {
	_c.Run(run)
	return _c
}

// JwkGet provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) JwkGet(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption) (*pkg.JwkGetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JwkGet")
	}

	var r0 *pkg.JwkGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) (*pkg.JwkGetResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) *pkg.JwkGetResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.JwkGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseClient_JwkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JwkGet'
type MockBaseClient_JwkGet_Call struct {
	*mock.Call
}

// JwkGet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.JwkGetRequest
//   - opts ...grpc.CallOption
func (_e *MockBaseClient_Expecter) JwkGet(ctx interface{}, req interface{}, opts ...interface{}) *MockBaseClient_JwkGet_Call {
	return &MockBaseClient_JwkGet_Call{Call: _e.mock.On("JwkGet",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockBaseClient_JwkGet_Call) Run(run func(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption)) *MockBaseClient_JwkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.JwkGetRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.JwkGetRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBaseClient_JwkGet_Call) Return(v *pkg.JwkGetResponse, err error) *MockBaseClient_JwkGet_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseClient_JwkGet_Call) RunAndReturn(run func(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption) (*pkg.JwkGetResponse, error)) *MockBaseClient_JwkGet_Call {
	_c.Call.Return(run)
	return _c
}

// JwkList provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) JwkList(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption) (*pkg.JwkListResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JwkList")
	}

	var r0 *pkg.JwkListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) (*pkg.JwkListResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) *pkg.JwkListResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.JwkListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseClient_JwkList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JwkList'
type MockBaseClient_JwkList_Call struct {
	*mock.Call
}

// JwkList is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.JwkListRequest
//   - opts ...grpc.CallOption
func (_e *MockBaseClient_Expecter) JwkList(ctx interface{}, req interface{}, opts ...interface{}) *MockBaseClient_JwkList_Call {
	return &MockBaseClient_JwkList_Call{Call: _e.mock.On("JwkList",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockBaseClient_JwkList_Call) Run(run func(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption)) *MockBaseClient_JwkList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.JwkListRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.JwkListRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBaseClient_JwkList_Call) Return(v *pkg.JwkListResponse, err error) *MockBaseClient_JwkList_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseClient_JwkList_Call) RunAndReturn(run func(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption) (*pkg.JwkListResponse, error)) *MockBaseClient_JwkList_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) Status(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption) (*pkg.StatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *pkg.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) (*pkg.StatusResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) *pkg.StatusResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockBaseClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.StatusRequest
//   - opts ...grpc.CallOption
func (_e *MockBaseClient_Expecter) Status(ctx interface{}, req interface{}, opts ...interface{}) *MockBaseClient_Status_Call {
	return &MockBaseClient_Status_Call{Call: _e.mock.On("Status",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockBaseClient_Status_Call) Run(run func(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption)) *MockBaseClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.StatusRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.StatusRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBaseClient_Status_Call) Return(v *pkg.StatusResponse, err error) *MockBaseClient_Status_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseClient_Status_Call) RunAndReturn(run func(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption) (*pkg.StatusResponse, error)) *MockBaseClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// UnaryEcho provides a mock function for the type MockBaseClient
func (_mock *MockBaseClient) UnaryEcho(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnaryEcho")
	}

	var r0 *golibproto.UnaryEchoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) *golibproto.UnaryEchoResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golibproto.UnaryEchoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseClient_UnaryEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnaryEcho'
type MockBaseClient_UnaryEcho_Call struct {
	*mock.Call
}

// UnaryEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - req *golibproto.UnaryEchoRequest
//   - opts ...grpc.CallOption
func (_e *MockBaseClient_Expecter) UnaryEcho(ctx interface{}, req interface{}, opts ...interface{}) *MockBaseClient_UnaryEcho_Call {
	return &MockBaseClient_UnaryEcho_Call{Call: _e.mock.On("UnaryEcho",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockBaseClient_UnaryEcho_Call) Run(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption)) *MockBaseClient_UnaryEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *golibproto.UnaryEchoRequest
		if args[1] != nil {
			arg1 = args[1].(*golibproto.UnaryEchoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBaseClient_UnaryEcho_Call) Return(unaryEchoResponse *golibproto.UnaryEchoResponse, err error) *MockBaseClient_UnaryEcho_Call {
	_c.Call.Return(unaryEchoResponse, err)
	return _c
}

func (_c *MockBaseClient_UnaryEcho_Call) RunAndReturn(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)) *MockBaseClient_UnaryEcho_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ClaimsSign provides a mock function for the type MockClient
func (_mock *MockClient) ClaimsSign(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption) (*pkg.ClaimsSignResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ClaimsSign")
	}

	var r0 *pkg.ClaimsSignResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) (*pkg.ClaimsSignResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) *pkg.ClaimsSignResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.ClaimsSignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.ClaimsSignRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ClaimsSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimsSign'
type MockClient_ClaimsSign_Call struct {
	*mock.Call
}

// ClaimsSign is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.ClaimsSignRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) ClaimsSign(ctx interface{}, req interface{}, opts ...interface{}) *MockClient_ClaimsSign_Call {
	return &MockClient_ClaimsSign_Call{Call: _e.mock.On("ClaimsSign",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockClient_ClaimsSign_Call) Run(run func(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption)) *MockClient_ClaimsSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.ClaimsSignRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.ClaimsSignRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ClaimsSign_Call) Return(v *pkg.ClaimsSignResponse, err error) *MockClient_ClaimsSign_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_ClaimsSign_Call) RunAndReturn(run func(ctx context.Context, req *pkg.ClaimsSignRequest, opts ...grpc.CallOption) (*pkg.ClaimsSignResponse, error)) *MockClient_ClaimsSign_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() {
	_mock.Called()
	return
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// JwkGet provides a mock function for the type MockClient
func (_mock *MockClient) JwkGet(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption) (*pkg.JwkGetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JwkGet")
	}

	var r0 *pkg.JwkGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) (*pkg.JwkGetResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) *pkg.JwkGetResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.JwkGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.JwkGetRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JwkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JwkGet'
type MockClient_JwkGet_Call struct {
	*mock.Call
}

// JwkGet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.JwkGetRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JwkGet(ctx interface{}, req interface{}, opts ...interface{}) *MockClient_JwkGet_Call {
	return &MockClient_JwkGet_Call{Call: _e.mock.On("JwkGet",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockClient_JwkGet_Call) Run(run func(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption)) *MockClient_JwkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.JwkGetRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.JwkGetRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JwkGet_Call) Return(v *pkg.JwkGetResponse, err error) *MockClient_JwkGet_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JwkGet_Call) RunAndReturn(run func(ctx context.Context, req *pkg.JwkGetRequest, opts ...grpc.CallOption) (*pkg.JwkGetResponse, error)) *MockClient_JwkGet_Call {
	_c.Call.Return(run)
	return _c
}

// JwkList provides a mock function for the type MockClient
func (_mock *MockClient) JwkList(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption) (*pkg.JwkListResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JwkList")
	}

	var r0 *pkg.JwkListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) (*pkg.JwkListResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) *pkg.JwkListResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.JwkListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.JwkListRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JwkList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JwkList'
type MockClient_JwkList_Call struct {
	*mock.Call
}

// JwkList is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.JwkListRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JwkList(ctx interface{}, req interface{}, opts ...interface{}) *MockClient_JwkList_Call {
	return &MockClient_JwkList_Call{Call: _e.mock.On("JwkList",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockClient_JwkList_Call) Run(run func(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption)) *MockClient_JwkList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.JwkListRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.JwkListRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JwkList_Call) Return(v *pkg.JwkListResponse, err error) *MockClient_JwkList_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JwkList_Call) RunAndReturn(run func(ctx context.Context, req *pkg.JwkListRequest, opts ...grpc.CallOption) (*pkg.JwkListResponse, error)) *MockClient_JwkList_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockClient
func (_mock *MockClient) Keys() map[string]*pkg.JwkConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 map[string]*pkg.JwkConfig
	if returnFunc, ok := ret.Get(0).(func() map[string]*pkg.JwkConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*pkg.JwkConfig)
		}
	}
	return r0
}

// MockClient_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockClient_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockClient_Expecter) Keys() *MockClient_Keys_Call {
	return &MockClient_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockClient_Keys_Call) Run(run func()) *MockClient_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Keys_Call) Return(stringToV map[string]*pkg.JwkConfig) *MockClient_Keys_Call {
	_c.Call.Return(stringToV)
	return _c
}

func (_c *MockClient_Keys_Call) RunAndReturn(run func() map[string]*pkg.JwkConfig) *MockClient_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Recipients provides a mock function for the type MockClient
func (_mock *MockClient) Recipients() pkg.JwkRecipients {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recipients")
	}

	var r0 pkg.JwkRecipients
	if returnFunc, ok := ret.Get(0).(func() pkg.JwkRecipients); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.JwkRecipients)
		}
	}
	return r0
}

// MockClient_Recipients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recipients'
type MockClient_Recipients_Call struct {
	*mock.Call
}

// Recipients is a helper method to define mock.On call
func (_e *MockClient_Expecter) Recipients() *MockClient_Recipients_Call {
	return &MockClient_Recipients_Call{Call: _e.mock.On("Recipients")}
}

func (_c *MockClient_Recipients_Call) Run(run func()) *MockClient_Recipients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Recipients_Call) Return(v pkg.JwkRecipients) *MockClient_Recipients_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockClient_Recipients_Call) RunAndReturn(run func() pkg.JwkRecipients) *MockClient_Recipients_Call {
	_c.Call.Return(run)
	return _c
}

// Sources provides a mock function for the type MockClient
func (_mock *MockClient) Sources() *pkg.JwkPublicSources {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sources")
	}

	var r0 *pkg.JwkPublicSources
	if returnFunc, ok := ret.Get(0).(func() *pkg.JwkPublicSources); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.JwkPublicSources)
		}
	}
	return r0
}

// MockClient_Sources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sources'
type MockClient_Sources_Call struct {
	*mock.Call
}

// Sources is a helper method to define mock.On call
func (_e *MockClient_Expecter) Sources() *MockClient_Sources_Call {
	return &MockClient_Sources_Call{Call: _e.mock.On("Sources")}
}

func (_c *MockClient_Sources_Call) Run(run func()) *MockClient_Sources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Sources_Call) Return(v *pkg.JwkPublicSources) *MockClient_Sources_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockClient_Sources_Call) RunAndReturn(run func() *pkg.JwkPublicSources) *MockClient_Sources_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockClient
func (_mock *MockClient) Status(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption) (*pkg.StatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *pkg.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) (*pkg.StatusResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) *pkg.StatusResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pkg.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - req *pkg.StatusRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) Status(ctx interface{}, req interface{}, opts ...interface{}) *MockClient_Status_Call {
	return &MockClient_Status_Call{Call: _e.mock.On("Status",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockClient_Status_Call) Run(run func(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption)) *MockClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pkg.StatusRequest
		if args[1] != nil {
			arg1 = args[1].(*pkg.StatusRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Status_Call) Return(v *pkg.StatusResponse, err error) *MockClient_Status_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_Status_Call) RunAndReturn(run func(ctx context.Context, req *pkg.StatusRequest, opts ...grpc.CallOption) (*pkg.StatusResponse, error)) *MockClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// UnaryEcho provides a mock function for the type MockClient
func (_mock *MockClient) UnaryEcho(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnaryEcho")
	}

	var r0 *golibproto.UnaryEchoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) *golibproto.UnaryEchoResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golibproto.UnaryEchoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UnaryEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnaryEcho'
type MockClient_UnaryEcho_Call struct {
	*mock.Call
}

// UnaryEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - req *golibproto.UnaryEchoRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) UnaryEcho(ctx interface{}, req interface{}, opts ...interface{}) *MockClient_UnaryEcho_Call {
	return &MockClient_UnaryEcho_Call{Call: _e.mock.On("UnaryEcho",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockClient_UnaryEcho_Call) Run(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption)) *MockClient_UnaryEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *golibproto.UnaryEchoRequest
		if args[1] != nil {
			arg1 = args[1].(*golibproto.UnaryEchoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_UnaryEcho_Call) Return(unaryEchoResponse *golibproto.UnaryEchoResponse, err error) *MockClient_UnaryEcho_Call {
	_c.Call.Return(unaryEchoResponse, err)
	return _c
}

func (_c *MockClient_UnaryEcho_Call) RunAndReturn(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)) *MockClient_UnaryEcho_Call {
	_c.Call.Return(run)
	return _c
}
