// Code generated by ogen, DO NOT EDIT.

package codegen

// OperationName is the ogen operation name
type OperationName = string

const (
	GetPublicKeyOperation   OperationName = "GetPublicKey"
	HealthcheckOperation    OperationName = "Healthcheck"
	ListPublicKeysOperation OperationName = "ListPublicKeys"
	PingOperation           OperationName = "Ping"
	SignClaimsOperation     OperationName = "SignClaims"
)
