// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"

	"github.com/a-novel-kit/jwt/jwa"
	"github.com/a-novel/service-json-keys/internal/dao"
	"github.com/a-novel/service-json-keys/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJwkGenRepositorySearch creates a new instance of MockJwkGenRepositorySearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenRepositorySearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenRepositorySearch {
	mock := &MockJwkGenRepositorySearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenRepositorySearch is an autogenerated mock type for the JwkGenRepositorySearch type
type MockJwkGenRepositorySearch struct {
	mock.Mock
}

type MockJwkGenRepositorySearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenRepositorySearch) EXPECT() *MockJwkGenRepositorySearch_Expecter {
	return &MockJwkGenRepositorySearch_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenRepositorySearch
func (_mock *MockJwkGenRepositorySearch) Exec(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) ([]*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) []*dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenRepositorySearch_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenRepositorySearch_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSearchRequest
func (_e *MockJwkGenRepositorySearch_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkGenRepositorySearch_Exec_Call {
	return &MockJwkGenRepositorySearch_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenRepositorySearch_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSearchRequest)) *MockJwkGenRepositorySearch_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenRepositorySearch_Exec_Call) Return(jwks []*dao.Jwk, err error) *MockJwkGenRepositorySearch_Exec_Call {
	_c.Call.Return(jwks, err)
	return _c
}

func (_c *MockJwkGenRepositorySearch_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error)) *MockJwkGenRepositorySearch_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGenRepositoryInsert creates a new instance of MockJwkGenRepositoryInsert. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenRepositoryInsert(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenRepositoryInsert {
	mock := &MockJwkGenRepositoryInsert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenRepositoryInsert is an autogenerated mock type for the JwkGenRepositoryInsert type
type MockJwkGenRepositoryInsert struct {
	mock.Mock
}

type MockJwkGenRepositoryInsert_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenRepositoryInsert) EXPECT() *MockJwkGenRepositoryInsert_Expecter {
	return &MockJwkGenRepositoryInsert_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenRepositoryInsert
func (_mock *MockJwkGenRepositoryInsert) Exec(ctx context.Context, request *dao.JwkInsertRequest) (*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkInsertRequest) (*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkInsertRequest) *dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenRepositoryInsert_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenRepositoryInsert_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkInsertRequest
func (_e *MockJwkGenRepositoryInsert_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkGenRepositoryInsert_Exec_Call {
	return &MockJwkGenRepositoryInsert_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenRepositoryInsert_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkInsertRequest)) *MockJwkGenRepositoryInsert_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenRepositoryInsert_Exec_Call) Return(jwk *dao.Jwk, err error) *MockJwkGenRepositoryInsert_Exec_Call {
	_c.Call.Return(jwk, err)
	return _c
}

func (_c *MockJwkGenRepositoryInsert_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkInsertRequest) (*dao.Jwk, error)) *MockJwkGenRepositoryInsert_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGenServiceExtract creates a new instance of MockJwkGenServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGenServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGenServiceExtract {
	mock := &MockJwkGenServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGenServiceExtract is an autogenerated mock type for the JwkGenServiceExtract type
type MockJwkGenServiceExtract struct {
	mock.Mock
}

type MockJwkGenServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGenServiceExtract) EXPECT() *MockJwkGenServiceExtract_Expecter {
	return &MockJwkGenServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGenServiceExtract
func (_mock *MockJwkGenServiceExtract) Exec(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGenServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGenServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkExtractRequest
func (_e *MockJwkGenServiceExtract_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkGenServiceExtract_Exec_Call {
	return &MockJwkGenServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGenServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *services.JwkExtractRequest)) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGenServiceExtract_Exec_Call) Return(v *services.Jwk, err error) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkGenServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error)) *MockJwkGenServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkPrivateSource creates a new instance of MockJwkPrivateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkPrivateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkPrivateSource {
	mock := &MockJwkPrivateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkPrivateSource is an autogenerated mock type for the JwkPrivateSource type
type MockJwkPrivateSource struct {
	mock.Mock
}

type MockJwkPrivateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkPrivateSource) EXPECT() *MockJwkPrivateSource_Expecter {
	return &MockJwkPrivateSource_Expecter{mock: &_m.Mock}
}

// SearchKeys provides a mock function for the type MockJwkPrivateSource
func (_mock *MockJwkPrivateSource) SearchKeys(ctx context.Context, usage string) ([]*jwa.JWK, error) {
	ret := _mock.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for SearchKeys")
	}

	var r0 []*jwa.JWK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*jwa.JWK, error)); ok {
		return returnFunc(ctx, usage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*jwa.JWK); ok {
		r0 = returnFunc(ctx, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jwa.JWK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, usage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkPrivateSource_SearchKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKeys'
type MockJwkPrivateSource_SearchKeys_Call struct {
	*mock.Call
}

// SearchKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - usage string
func (_e *MockJwkPrivateSource_Expecter) SearchKeys(ctx interface{}, usage interface{}) *MockJwkPrivateSource_SearchKeys_Call {
	return &MockJwkPrivateSource_SearchKeys_Call{Call: _e.mock.On("SearchKeys", ctx, usage)}
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) Run(run func(ctx context.Context, usage string)) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) Return(jWKs []*jwa.JWK, err error) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Return(jWKs, err)
	return _c
}

func (_c *MockJwkPrivateSource_SearchKeys_Call) RunAndReturn(run func(ctx context.Context, usage string) ([]*jwa.JWK, error)) *MockJwkPrivateSource_SearchKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkPublicSource creates a new instance of MockJwkPublicSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkPublicSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkPublicSource {
	mock := &MockJwkPublicSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkPublicSource is an autogenerated mock type for the JwkPublicSource type
type MockJwkPublicSource struct {
	mock.Mock
}

type MockJwkPublicSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkPublicSource) EXPECT() *MockJwkPublicSource_Expecter {
	return &MockJwkPublicSource_Expecter{mock: &_m.Mock}
}

// SearchKeys provides a mock function for the type MockJwkPublicSource
func (_mock *MockJwkPublicSource) SearchKeys(ctx context.Context, usage string) ([]*jwa.JWK, error) {
	ret := _mock.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for SearchKeys")
	}

	var r0 []*jwa.JWK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*jwa.JWK, error)); ok {
		return returnFunc(ctx, usage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*jwa.JWK); ok {
		r0 = returnFunc(ctx, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jwa.JWK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, usage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkPublicSource_SearchKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKeys'
type MockJwkPublicSource_SearchKeys_Call struct {
	*mock.Call
}

// SearchKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - usage string
func (_e *MockJwkPublicSource_Expecter) SearchKeys(ctx interface{}, usage interface{}) *MockJwkPublicSource_SearchKeys_Call {
	return &MockJwkPublicSource_SearchKeys_Call{Call: _e.mock.On("SearchKeys", ctx, usage)}
}

func (_c *MockJwkPublicSource_SearchKeys_Call) Run(run func(ctx context.Context, usage string)) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkPublicSource_SearchKeys_Call) Return(jWKs []*jwa.JWK, err error) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Return(jWKs, err)
	return _c
}

func (_c *MockJwkPublicSource_SearchKeys_Call) RunAndReturn(run func(ctx context.Context, usage string) ([]*jwa.JWK, error)) *MockJwkPublicSource_SearchKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSearchRepository creates a new instance of MockJwkSearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSearchRepository {
	mock := &MockJwkSearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSearchRepository is an autogenerated mock type for the JwkSearchRepository type
type MockJwkSearchRepository struct {
	mock.Mock
}

type MockJwkSearchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSearchRepository) EXPECT() *MockJwkSearchRepository_Expecter {
	return &MockJwkSearchRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSearchRepository
func (_mock *MockJwkSearchRepository) Exec(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) ([]*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSearchRequest) []*dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSearchRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSearchRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSearchRequest
func (_e *MockJwkSearchRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkSearchRepository_Exec_Call {
	return &MockJwkSearchRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSearchRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSearchRequest)) *MockJwkSearchRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSearchRepository_Exec_Call) Return(jwks []*dao.Jwk, err error) *MockJwkSearchRepository_Exec_Call {
	_c.Call.Return(jwks, err)
	return _c
}

func (_c *MockJwkSearchRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSearchRequest) ([]*dao.Jwk, error)) *MockJwkSearchRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSearchServiceExtract creates a new instance of MockJwkSearchServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSearchServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSearchServiceExtract {
	mock := &MockJwkSearchServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSearchServiceExtract is an autogenerated mock type for the JwkSearchServiceExtract type
type MockJwkSearchServiceExtract struct {
	mock.Mock
}

type MockJwkSearchServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSearchServiceExtract) EXPECT() *MockJwkSearchServiceExtract_Expecter {
	return &MockJwkSearchServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSearchServiceExtract
func (_mock *MockJwkSearchServiceExtract) Exec(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSearchServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSearchServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkExtractRequest
func (_e *MockJwkSearchServiceExtract_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkSearchServiceExtract_Exec_Call {
	return &MockJwkSearchServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *services.JwkExtractRequest)) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) Return(v *services.Jwk, err error) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkSearchServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error)) *MockJwkSearchServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSelectRepository creates a new instance of MockJwkSelectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSelectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSelectRepository {
	mock := &MockJwkSelectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSelectRepository is an autogenerated mock type for the JwkSelectRepository type
type MockJwkSelectRepository struct {
	mock.Mock
}

type MockJwkSelectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSelectRepository) EXPECT() *MockJwkSelectRepository_Expecter {
	return &MockJwkSelectRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSelectRepository
func (_mock *MockJwkSelectRepository) Exec(ctx context.Context, request *dao.JwkSelectRequest) (*dao.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSelectRequest) (*dao.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JwkSelectRequest) *dao.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JwkSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSelectRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSelectRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JwkSelectRequest
func (_e *MockJwkSelectRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkSelectRepository_Exec_Call {
	return &MockJwkSelectRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSelectRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.JwkSelectRequest)) *MockJwkSelectRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JwkSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JwkSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSelectRepository_Exec_Call) Return(jwk *dao.Jwk, err error) *MockJwkSelectRepository_Exec_Call {
	_c.Call.Return(jwk, err)
	return _c
}

func (_c *MockJwkSelectRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JwkSelectRequest) (*dao.Jwk, error)) *MockJwkSelectRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkSelectServiceExtract creates a new instance of MockJwkSelectServiceExtract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkSelectServiceExtract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkSelectServiceExtract {
	mock := &MockJwkSelectServiceExtract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkSelectServiceExtract is an autogenerated mock type for the JwkSelectServiceExtract type
type MockJwkSelectServiceExtract struct {
	mock.Mock
}

type MockJwkSelectServiceExtract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkSelectServiceExtract) EXPECT() *MockJwkSelectServiceExtract_Expecter {
	return &MockJwkSelectServiceExtract_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkSelectServiceExtract
func (_mock *MockJwkSelectServiceExtract) Exec(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkExtractRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkExtractRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkSelectServiceExtract_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkSelectServiceExtract_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkExtractRequest
func (_e *MockJwkSelectServiceExtract_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkSelectServiceExtract_Exec_Call {
	return &MockJwkSelectServiceExtract_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) Run(run func(ctx context.Context, request *services.JwkExtractRequest)) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkExtractRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkExtractRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) Return(v *services.Jwk, err error) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkSelectServiceExtract_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkExtractRequest) (*services.Jwk, error)) *MockJwkSelectServiceExtract_Exec_Call {
	_c.Call.Return(run)
	return _c
}
