// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-json-keys/v2/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaimsSignService creates a new instance of MockClaimsSignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsSignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsSignService {
	mock := &MockClaimsSignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaimsSignService is an autogenerated mock type for the ClaimsSignService type
type MockClaimsSignService struct {
	mock.Mock
}

type MockClaimsSignService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaimsSignService) EXPECT() *MockClaimsSignService_Expecter {
	return &MockClaimsSignService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockClaimsSignService
func (_mock *MockClaimsSignService) Exec(ctx context.Context, request *services.ClaimsSignRequest) (string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ClaimsSignRequest) (string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ClaimsSignRequest) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ClaimsSignRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaimsSignService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockClaimsSignService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ClaimsSignRequest
func (_e *MockClaimsSignService_Expecter) Exec(ctx interface{}, request interface{}) *MockClaimsSignService_Exec_Call {
	return &MockClaimsSignService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockClaimsSignService_Exec_Call) Run(run func(ctx context.Context, request *services.ClaimsSignRequest)) *MockClaimsSignService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ClaimsSignRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ClaimsSignRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClaimsSignService_Exec_Call) Return(s string, err error) *MockClaimsSignService_Exec_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClaimsSignService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ClaimsSignRequest) (string, error)) *MockClaimsSignService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkGetService creates a new instance of MockJwkGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkGetService {
	mock := &MockJwkGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkGetService is an autogenerated mock type for the JwkGetService type
type MockJwkGetService struct {
	mock.Mock
}

type MockJwkGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkGetService) EXPECT() *MockJwkGetService_Expecter {
	return &MockJwkGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkGetService
func (_mock *MockJwkGetService) Exec(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSelectRequest
func (_e *MockJwkGetService_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkGetService_Exec_Call {
	return &MockJwkGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkGetService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSelectRequest)) *MockJwkGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkGetService_Exec_Call) Return(v *services.Jwk, err error) *MockJwkGetService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJwkGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error)) *MockJwkGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwkListService creates a new instance of MockJwkListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwkListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwkListService {
	mock := &MockJwkListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwkListService is an autogenerated mock type for the JwkListService type
type MockJwkListService struct {
	mock.Mock
}

type MockJwkListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwkListService) EXPECT() *MockJwkListService_Expecter {
	return &MockJwkListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJwkListService
func (_mock *MockJwkListService) Exec(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) ([]*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) []*services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwkListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJwkListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSearchRequest
func (_e *MockJwkListService_Expecter) Exec(ctx interface{}, request interface{}) *MockJwkListService_Exec_Call {
	return &MockJwkListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJwkListService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSearchRequest)) *MockJwkListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwkListService_Exec_Call) Return(vs []*services.Jwk, err error) *MockJwkListService_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockJwkListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error)) *MockJwkListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
