// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-json-keys/v2/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGrpcClaimsSignService creates a new instance of MockGrpcClaimsSignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcClaimsSignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcClaimsSignService {
	mock := &MockGrpcClaimsSignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcClaimsSignService is an autogenerated mock type for the GrpcClaimsSignService type
type MockGrpcClaimsSignService struct {
	mock.Mock
}

type MockGrpcClaimsSignService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcClaimsSignService) EXPECT() *MockGrpcClaimsSignService_Expecter {
	return &MockGrpcClaimsSignService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcClaimsSignService
func (_mock *MockGrpcClaimsSignService) Exec(ctx context.Context, request *services.ClaimsSignRequest) (string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ClaimsSignRequest) (string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ClaimsSignRequest) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ClaimsSignRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcClaimsSignService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcClaimsSignService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ClaimsSignRequest
func (_e *MockGrpcClaimsSignService_Expecter) Exec(ctx interface{}, request interface{}) *MockGrpcClaimsSignService_Exec_Call {
	return &MockGrpcClaimsSignService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcClaimsSignService_Exec_Call) Run(run func(ctx context.Context, request *services.ClaimsSignRequest)) *MockGrpcClaimsSignService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ClaimsSignRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ClaimsSignRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcClaimsSignService_Exec_Call) Return(s string, err error) *MockGrpcClaimsSignService_Exec_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGrpcClaimsSignService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ClaimsSignRequest) (string, error)) *MockGrpcClaimsSignService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrpcJwkGetService creates a new instance of MockGrpcJwkGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcJwkGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcJwkGetService {
	mock := &MockGrpcJwkGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcJwkGetService is an autogenerated mock type for the GrpcJwkGetService type
type MockGrpcJwkGetService struct {
	mock.Mock
}

type MockGrpcJwkGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcJwkGetService) EXPECT() *MockGrpcJwkGetService_Expecter {
	return &MockGrpcJwkGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcJwkGetService
func (_mock *MockGrpcJwkGetService) Exec(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcJwkGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcJwkGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSelectRequest
func (_e *MockGrpcJwkGetService_Expecter) Exec(ctx interface{}, request interface{}) *MockGrpcJwkGetService_Exec_Call {
	return &MockGrpcJwkGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcJwkGetService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSelectRequest)) *MockGrpcJwkGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcJwkGetService_Exec_Call) Return(v *services.Jwk, err error) *MockGrpcJwkGetService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockGrpcJwkGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error)) *MockGrpcJwkGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrpcJwkListService creates a new instance of MockGrpcJwkListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcJwkListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcJwkListService {
	mock := &MockGrpcJwkListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcJwkListService is an autogenerated mock type for the GrpcJwkListService type
type MockGrpcJwkListService struct {
	mock.Mock
}

type MockGrpcJwkListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcJwkListService) EXPECT() *MockGrpcJwkListService_Expecter {
	return &MockGrpcJwkListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcJwkListService
func (_mock *MockGrpcJwkListService) Exec(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) ([]*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) []*services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcJwkListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcJwkListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSearchRequest
func (_e *MockGrpcJwkListService_Expecter) Exec(ctx interface{}, request interface{}) *MockGrpcJwkListService_Exec_Call {
	return &MockGrpcJwkListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcJwkListService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSearchRequest)) *MockGrpcJwkListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcJwkListService_Exec_Call) Return(vs []*services.Jwk, err error) *MockGrpcJwkListService_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockGrpcJwkListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error)) *MockGrpcJwkListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestJwkGetService creates a new instance of MockRestJwkGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestJwkGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestJwkGetService {
	mock := &MockRestJwkGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestJwkGetService is an autogenerated mock type for the RestJwkGetService type
type MockRestJwkGetService struct {
	mock.Mock
}

type MockRestJwkGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestJwkGetService) EXPECT() *MockRestJwkGetService_Expecter {
	return &MockRestJwkGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestJwkGetService
func (_mock *MockRestJwkGetService) Exec(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) (*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSelectRequest) *services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestJwkGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestJwkGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSelectRequest
func (_e *MockRestJwkGetService_Expecter) Exec(ctx interface{}, request interface{}) *MockRestJwkGetService_Exec_Call {
	return &MockRestJwkGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestJwkGetService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSelectRequest)) *MockRestJwkGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestJwkGetService_Exec_Call) Return(v *services.Jwk, err error) *MockRestJwkGetService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRestJwkGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSelectRequest) (*services.Jwk, error)) *MockRestJwkGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestJwkListService creates a new instance of MockRestJwkListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestJwkListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestJwkListService {
	mock := &MockRestJwkListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestJwkListService is an autogenerated mock type for the RestJwkListService type
type MockRestJwkListService struct {
	mock.Mock
}

type MockRestJwkListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestJwkListService) EXPECT() *MockRestJwkListService_Expecter {
	return &MockRestJwkListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestJwkListService
func (_mock *MockRestJwkListService) Exec(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*services.Jwk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) ([]*services.Jwk, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.JwkSearchRequest) []*services.Jwk); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.Jwk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.JwkSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestJwkListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestJwkListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.JwkSearchRequest
func (_e *MockRestJwkListService_Expecter) Exec(ctx interface{}, request interface{}) *MockRestJwkListService_Exec_Call {
	return &MockRestJwkListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestJwkListService_Exec_Call) Run(run func(ctx context.Context, request *services.JwkSearchRequest)) *MockRestJwkListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.JwkSearchRequest
		if args[1] != nil {
			arg1 = args[1].(*services.JwkSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestJwkListService_Exec_Call) Return(vs []*services.Jwk, err error) *MockRestJwkListService_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRestJwkListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.JwkSearchRequest) ([]*services.Jwk, error)) *MockRestJwkListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
