name: run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: a-novel-kit/workflows/generic-actions/renovate@master
        with:
          allowed_commands: '["^sh \\./scripts/post-upgrade-renovate.sh$"]'
          pat: ${{ secrets.ACTION_PAT }}
          with_node: true
